### ISSUE TITLE
Runtime error on import { hbs } from 'ember-cli-htmlbars'

### ISSUE THREAD

**Issue by iamareebjamal** [storybookjs/ember-cli-storybook#35]
```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at includes (http://localhost:6006/vendors~main.925bee91ab6e54312329.bundle.js:113614:31)
    at push../node_modules/resolve-package-path/lib/should-preserve-symlinks.js.module.exports (http://localhost:6006/vendors~main.925bee91ab6e54312329.bundle.js:113622:52)
    at Object.<anonymous> (http://localhost:6006/vendors~main.925bee91ab6e54312329.bundle.js:113404:25)
```

This happens because `ember-cli-htmlbars/utils.js` requires `hash-for-dep`
https://github.com/ember-cli/ember-cli-htmlbars/blob/aee846034a6b6772fef7675dad2156e69b40df8e/lib/utils.js#L5

`hash-for-dep/module-entry.js` requires `resolve-package-path`
https://github.com/stefanpenner/hash-for-dep/blob/f4cc06e526a36f83427b8ce1a6da2ea616112278/lib/module-entry.js#L3

Which accesses `process.execArgv` which is not defined on webpack's process shim
https://github.com/stefanpenner/resolve-package-path/blob/3e9b74512521c69609e84736e64d8e21c52a0c55/lib/should-preserve-symlinks.ts#L17

https://github.com/webpack/node-libs-browser/issues/78

Is this issue exclusive to me? Are others facing this as well? Am I missing some config

**Comment by iamareebjamal** [comment]
Even after manually editing `should-preserve-symlinks.js`, it proceeds but I get another error 

```
Object(...) is not a function
TypeError: Object(...) is not a function
```

I am surely missing something because everything works in the example repo https://github.com/storybookjs/storybook/tree/v5.3.18/examples/ember-cli/
This is the PR for reference - https://github.com/fossasia/open-event-frontend/pull/4325

**Comment by iamareebjamal** [comment]
Working now
