### ISSUE TITLE
Doesn't work with ember v3.21

### ISSUE THREAD

**Issue by afzal273** [storybookjs/ember-cli-storybook#49]
Getting the following error 
```bash
ember install @storybook/ember-cli-storybook
..../storybook-app/node_modules/ember-cli/lib/cli/index.js:69
module.exports = async function (options) {
                       ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (.../storybook-app/node_modules/ember-cli/bin/ember:31:11)
```

**Comment by afzal273** [comment]
Please ignore the issue, was using a very old node version :-/
